# Generated by Django 2.0.1 on 2018-02-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(blank=True, null=True, upload_to='media')),
                ('created', models.DateTimeField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='SenseIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('umidade', models.IntegerField(verbose_name='Umidade')),
                ('luz', models.IntegerField(verbose_name='Luz')),
                ('temperatura', models.FloatField(verbose_name='Temperatura')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='SenseOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('umidade', models.IntegerField(verbose_name='Umidade')),
                ('luz', models.IntegerField(verbose_name='Luz')),
                ('temperatura', models.FloatField(verbose_name='Temperatura')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
