# Generated by Django 2.0.1 on 2018-02-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensein',
            name='umidade',
            field=models.FloatField(verbose_name='Umidade'),
        ),
        migrations.AlterField(
            model_name='senseout',
            name='umidade',
            field=models.FloatField(verbose_name='Umidade'),
        ),
    ]
