# Generated by Django 2.0.1 on 2018-03-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180223_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.TextField(verbose_name='Acao')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.FileField(blank=True, upload_to='', verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
